// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using StartQuest.Infrastructure.Entities;

namespace StartQuest.Infrastructure.Context;

public partial class StartQuestContext : DbContext
{
    public StartQuestContext(DbContextOptions<StartQuestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.Email, "IXU_Users_Email")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.UserName, "IXU_Users_UserName")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.UserType, "IXU_Users_UserType")
                .IsUnique()
                .HasFilter("[UserType] = 'Admin' AND [DeletedAt] IS NULL AND [IsActive] = 1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordAlgo).HasMaxLength(50);
            entity.Property(e => e.PasswordHash).HasMaxLength(512);
            entity.Property(e => e.PasswordSalt).HasMaxLength(512);
            entity.Property(e => e.TwoFactorSecretKey).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(100);
            entity.Property(e => e.UserType)
                .HasMaxLength(50)
                .HasDefaultValue("User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}