// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class BattlePass
{
    public int Id { get; set; }

    public Guid PublicId { get; set; }

    public int TenantId { get; set; }

    public int CreatedByUserId { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime? StartAt { get; set; }

    public DateTime? EndAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<BattlePassItem> BattlePassItems { get; set; } = new List<BattlePassItem>();

    public virtual User CreatedByUser { get; set; } = null!;

    public virtual Tenant Tenant { get; set; } = null!;
}