// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class BattlePassItem
{
    public int Id { get; set; }

    public int BattlePassId { get; set; }

    public int WorkItemId { get; set; }

    public int Points { get; set; }

    public int SortOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual BattlePass BattlePass { get; set; } = null!;

    public virtual WorkItem WorkItem { get; set; } = null!;
}