// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class Tag
{
    public int Id { get; set; }

    public int TenantId { get; set; }

    public string Name { get; set; } = null!;

    public string? Color { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual Tenant Tenant { get; set; } = null!;

    public virtual ICollection<WorkItemTag> WorkItemTags { get; set; } = new List<WorkItemTag>();
}