// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class Tenant
{
    public int Id { get; set; }

    public Guid PublicId { get; set; }

    public int TypeId { get; set; }

    public int OwnerUserId { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<BattlePass> BattlePasses { get; set; } = new List<BattlePass>();

    public virtual ICollection<Craft> Crafts { get; set; } = new List<Craft>();

    public virtual User OwnerUser { get; set; } = null!;

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();

    public virtual ICollection<TenantMember> TenantMembers { get; set; } = new List<TenantMember>();

    public virtual ICollection<TimeSheetEntry> TimeSheetEntries { get; set; } = new List<TimeSheetEntry>();

    public virtual TenantType Type { get; set; } = null!;

    public virtual ICollection<WorkItem> WorkItems { get; set; } = new List<WorkItem>();
}