// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class User
{
    public int Id { get; set; }

    public Guid PublicId { get; set; }

    public string Email { get; set; } = null!;

    public string UserName { get; set; } = null!;

    public string UserType { get; set; } = null!;

    public string PasswordHash { get; set; } = null!;

    public string? PasswordSalt { get; set; }

    public string? PasswordAlgo { get; set; }

    public bool EmailConfirmed { get; set; }

    public bool IsLockedOut { get; set; }

    public DateTime? LockoutEndAt { get; set; }

    public int FailedAccessCount { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public string? TwoFactorSecretKey { get; set; }

    public string? TwoFactorBackupCodes { get; set; }

    public DateTime? TwoFactorLastUpdatedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<BattlePass> BattlePasses { get; set; } = new List<BattlePass>();

    public virtual ICollection<Craft> Crafts { get; set; } = new List<Craft>();

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();

    public virtual ICollection<TenantMember> TenantMembers { get; set; } = new List<TenantMember>();

    public virtual ICollection<Tenant> Tenants { get; set; } = new List<Tenant>();

    public virtual ICollection<TimeSheetEntry> TimeSheetEntries { get; set; } = new List<TimeSheetEntry>();

    public virtual ICollection<UserRefreshToken> UserRefreshTokens { get; set; } = new List<UserRefreshToken>();

    public virtual ICollection<WorkItemAssignment> WorkItemAssignmentAssignedByUsers { get; set; } = new List<WorkItemAssignment>();

    public virtual ICollection<WorkItemAssignment> WorkItemAssignmentUsers { get; set; } = new List<WorkItemAssignment>();

    public virtual ICollection<WorkItem> WorkItems { get; set; } = new List<WorkItem>();
}