// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class WorkItemTag
{
    public int Id { get; set; }

    public int WorkItemId { get; set; }

    public int TagId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Tag Tag { get; set; } = null!;

    public virtual WorkItem WorkItem { get; set; } = null!;
}