// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class WorkItemSchedule
{
    public int Id { get; set; }

    public int WorkItemId { get; set; }

    public int ScheduleTypeId { get; set; }

    public int? RecurrenceTypeId { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime? EndAt { get; set; }

    public string TimeZone { get; set; } = null!;

    public int Interval { get; set; }

    public string? DaysOfWeek { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual RecurrenceType? RecurrenceType { get; set; }

    public virtual ScheduleType ScheduleType { get; set; } = null!;

    public virtual WorkItem WorkItem { get; set; } = null!;

    public virtual ICollection<WorkItemOccurrence> WorkItemOccurrences { get; set; } = new List<WorkItemOccurrence>();
}