// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class WorkItemAssignment
{
    public int Id { get; set; }

    public int WorkItemId { get; set; }

    public int UserId { get; set; }

    public int AssignedByUserId { get; set; }

    public bool IsPrimary { get; set; }

    public DateTime AssignedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual User AssignedByUser { get; set; } = null!;

    public virtual User User { get; set; } = null!;

    public virtual WorkItem WorkItem { get; set; } = null!;
}