// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class WorkItem
{
    public int Id { get; set; }

    public Guid PublicId { get; set; }

    public int TenantId { get; set; }

    public int ProjectId { get; set; }

    public int TypeId { get; set; }

    public int StatusId { get; set; }

    public int? ParentId { get; set; }

    public int CreatedByUserId { get; set; }

    public int Number { get; set; }

    public string Code { get; set; } = null!;

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime? DueAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<BattlePassItem> BattlePassItems { get; set; } = new List<BattlePassItem>();

    public virtual User CreatedByUser { get; set; } = null!;

    public virtual ICollection<WorkItem> InverseParent { get; set; } = new List<WorkItem>();

    public virtual WorkItem? Parent { get; set; }

    public virtual Project Project { get; set; } = null!;

    public virtual WorkItemStatus Status { get; set; } = null!;

    public virtual Tenant Tenant { get; set; } = null!;

    public virtual ICollection<TimeSheetEntry> TimeSheetEntries { get; set; } = new List<TimeSheetEntry>();

    public virtual WorkItemType Type { get; set; } = null!;

    public virtual ICollection<WorkItemAssignment> WorkItemAssignments { get; set; } = new List<WorkItemAssignment>();

    public virtual ICollection<WorkItemCraftReward> WorkItemCraftRewards { get; set; } = new List<WorkItemCraftReward>();

    public virtual ICollection<WorkItemOccurrence> WorkItemOccurrences { get; set; } = new List<WorkItemOccurrence>();

    public virtual ICollection<WorkItemSchedule> WorkItemSchedules { get; set; } = new List<WorkItemSchedule>();

    public virtual ICollection<WorkItemSkillReward> WorkItemSkillRewards { get; set; } = new List<WorkItemSkillReward>();

    public virtual ICollection<WorkItemTag> WorkItemTags { get; set; } = new List<WorkItemTag>();
}