// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace StartQuest.Infrastructure.Entities;

public partial class WorkItemOccurrence
{
    public long Id { get; set; }

    public Guid PublicId { get; set; }

    public int WorkItemId { get; set; }

    public int ScheduleId { get; set; }

    public int StatusId { get; set; }

    public DateTime ScheduledStartAt { get; set; }

    public DateTime? ScheduledEndAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual WorkItemSchedule Schedule { get; set; } = null!;

    public virtual OccurrenceStatus Status { get; set; } = null!;

    public virtual ICollection<TimeSheetEntry> TimeSheetEntries { get; set; } = new List<TimeSheetEntry>();

    public virtual WorkItem WorkItem { get; set; } = null!;
}