G// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using StartQuest.Infrastructure.Entities;

namespace StartQuest.Infrastructure.Context;

public partial class StartQuestContext : DbContext
{
    public StartQuestContext(DbContextOptions<StartQuestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BattlePass> BattlePasses { get; set; }

    public virtual DbSet<BattlePassItem> BattlePassItems { get; set; }

    public virtual DbSet<Craft> Crafts { get; set; }

    public virtual DbSet<OccurrenceStatus> OccurrenceStatuses { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<ProjectStatus> ProjectStatuses { get; set; }

    public virtual DbSet<RecurrenceType> RecurrenceTypes { get; set; }

    public virtual DbSet<ScheduleType> ScheduleTypes { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<Tenant> Tenants { get; set; }

    public virtual DbSet<TenantMember> TenantMembers { get; set; }

    public virtual DbSet<TenantRole> TenantRoles { get; set; }

    public virtual DbSet<TenantType> TenantTypes { get; set; }

    public virtual DbSet<TimeSheetEntry> TimeSheetEntries { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRefreshToken> UserRefreshTokens { get; set; }

    public virtual DbSet<WorkItem> WorkItems { get; set; }

    public virtual DbSet<WorkItemAssignment> WorkItemAssignments { get; set; }

    public virtual DbSet<WorkItemCraftReward> WorkItemCraftRewards { get; set; }

    public virtual DbSet<WorkItemOccurrence> WorkItemOccurrences { get; set; }

    public virtual DbSet<WorkItemSchedule> WorkItemSchedules { get; set; }

    public virtual DbSet<WorkItemSkillReward> WorkItemSkillRewards { get; set; }

    public virtual DbSet<WorkItemStatus> WorkItemStatuses { get; set; }

    public virtual DbSet<WorkItemTag> WorkItemTags { get; set; }

    public virtual DbSet<WorkItemType> WorkItemTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BattlePass>(entity =>
        {
            entity.HasIndex(e => e.PublicId, "IXU_BattlePasses_PublicId").IsUnique();

            entity.HasIndex(e => e.TenantId, "IX_BattlePasses_TenantId").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.BattlePasses)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Tenant).WithMany(p => p.BattlePasses)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<BattlePassItem>(entity =>
        {
            entity.HasIndex(e => new { e.BattlePassId, e.WorkItemId }, "IXU_BattlePassItems_BattlePassId_WorkItemId")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.WorkItemId, "IX_BattlePassItems_WorkItemId").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.BattlePass).WithMany(p => p.BattlePassItems)
                .HasForeignKey(d => d.BattlePassId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.BattlePassItems)
                .HasForeignKey(d => d.WorkItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Craft>(entity =>
        {
            entity.HasIndex(e => e.PublicId, "IXU_Crafts_PublicId").IsUnique();

            entity.HasIndex(e => new { e.TenantId, e.Name }, "IXU_Crafts_TenantId_Name")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Crafts)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Tenant).WithMany(p => p.Crafts)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<OccurrenceStatus>(entity =>
        {
            entity.HasIndex(e => e.Code, "IXU_OccurrenceStatuses_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasIndex(e => e.PublicId, "IXU_Projects_PublicId").IsUnique();

            entity.HasIndex(e => new { e.TenantId, e.Key }, "IXU_Projects_TenantId_Key")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => new { e.TenantId, e.StatusId }, "IX_Projects_TenantId_StatusId").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Key).HasMaxLength(20);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Projects)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Status).WithMany(p => p.Projects)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Tenant).WithMany(p => p.Projects)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ProjectStatus>(entity =>
        {
            entity.HasIndex(e => e.Code, "IXU_ProjectStatuses_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<RecurrenceType>(entity =>
        {
            entity.HasIndex(e => e.Code, "IXU_RecurrenceTypes_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<ScheduleType>(entity =>
        {
            entity.HasIndex(e => e.Code, "IXU_ScheduleTypes_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<Skill>(entity =>
        {
            entity.HasIndex(e => e.PublicId, "IXU_Skills_PublicId").IsUnique();

            entity.HasIndex(e => new { e.TenantId, e.Name }, "IXU_Skills_TenantId_Name")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Level).HasDefaultValue(1);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Skills)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Tenant).WithMany(p => p.Skills)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasIndex(e => new { e.TenantId, e.Name }, "IXU_Tags_TenantId_Name")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Color).HasMaxLength(20);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);

            entity.HasOne(d => d.Tenant).WithMany(p => p.Tags)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Tenant>(entity =>
        {
            entity.HasIndex(e => e.PublicId, "IXU_Tenants_PublicId").IsUnique();

            entity.HasIndex(e => e.OwnerUserId, "IX_Tenants_OwnerUserId").HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.TypeId, "IX_Tenants_TypeId").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.OwnerUser).WithMany(p => p.Tenants)
                .HasForeignKey(d => d.OwnerUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Type).WithMany(p => p.Tenants)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TenantMember>(entity =>
        {
            entity.HasIndex(e => new { e.TenantId, e.UserId }, "IXU_TenantMembers_TenantId_UserId")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.UserId, "IX_TenantMembers_UserId").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.JoinedAt).HasDefaultValueSql("GETUTCDATE()");

            entity.HasOne(d => d.Role).WithMany(p => p.TenantMembers)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Tenant).WithMany(p => p.TenantMembers)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.User).WithMany(p => p.TenantMembers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TenantRole>(entity =>
        {
            entity.HasIndex(e => e.Code, "IXU_TenantRoles_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<TenantType>(entity =>
        {
            entity.HasIndex(e => e.Code, "IXU_TenantTypes_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<TimeSheetEntry>(entity =>
        {
            entity.HasIndex(e => e.PublicId, "IXU_TimeSheetEntries_PublicId").IsUnique();

            entity.HasIndex(e => new { e.UserId, e.StartedAt }, "IX_TimeSheetEntries_UserId_StartedAt").HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => new { e.WorkItemId, e.StartedAt }, "IX_TimeSheetEntries_WorkItemId_StartedAt").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.Occurrence).WithMany(p => p.TimeSheetEntries).HasForeignKey(d => d.OccurrenceId);

            entity.HasOne(d => d.Tenant).WithMany(p => p.TimeSheetEntries)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.User).WithMany(p => p.TimeSheetEntries)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.TimeSheetEntries)
                .HasForeignKey(d => d.WorkItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.Email, "IXU_Users_Email")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.PublicId, "IXU_Users_PublicId").IsUnique();

            entity.HasIndex(e => e.UserName, "IXU_Users_UserName")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.UserType, "IXU_Users_UserType")
                .IsUnique()
                .HasFilter("[UserType] = 'Admin' AND [DeletedAt] IS NULL AND [IsActive] = 1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordAlgo).HasMaxLength(50);
            entity.Property(e => e.PasswordHash).HasMaxLength(512);
            entity.Property(e => e.PasswordSalt).HasMaxLength(512);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");
            entity.Property(e => e.TwoFactorSecretKey).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(100);
            entity.Property(e => e.UserType)
                .HasMaxLength(50)
                .HasDefaultValue("User");
        });

        modelBuilder.Entity<UserRefreshToken>(entity =>
        {
            entity.HasIndex(e => e.Token, "IX_UserRefreshTokens_Token");

            entity.HasIndex(e => e.UserId, "IX_UserRefreshTokens_UserId");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ReasonRevoked).HasMaxLength(250);
            entity.Property(e => e.Token).HasMaxLength(500);

            entity.HasOne(d => d.User).WithMany(p => p.UserRefreshTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<WorkItem>(entity =>
        {
            entity.HasIndex(e => new { e.ProjectId, e.Number }, "IXU_WorkItems_ProjectId_Number")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.PublicId, "IXU_WorkItems_PublicId").IsUnique();

            entity.HasIndex(e => new { e.TenantId, e.Code }, "IXU_WorkItems_TenantId_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.ParentId, "IX_WorkItems_ParentId").HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => new { e.ProjectId, e.StatusId }, "IX_WorkItems_ProjectId_StatusId").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.WorkItems)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent).HasForeignKey(d => d.ParentId);

            entity.HasOne(d => d.Project).WithMany(p => p.WorkItems)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Status).WithMany(p => p.WorkItems)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Tenant).WithMany(p => p.WorkItems)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Type).WithMany(p => p.WorkItems)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WorkItemAssignment>(entity =>
        {
            entity.HasIndex(e => new { e.WorkItemId, e.UserId }, "IXU_WorkItemAssignments_WorkItemId_UserId")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => e.UserId, "IX_WorkItemAssignments_UserId").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.AssignedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.AssignedByUser).WithMany(p => p.WorkItemAssignmentAssignedByUsers)
                .HasForeignKey(d => d.AssignedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.User).WithMany(p => p.WorkItemAssignmentUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.WorkItemAssignments)
                .HasForeignKey(d => d.WorkItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WorkItemCraftReward>(entity =>
        {
            entity.HasIndex(e => new { e.WorkItemId, e.CraftId }, "IXU_WorkItemCraftRewards_WorkItemId_CraftId")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");

            entity.HasOne(d => d.Craft).WithMany(p => p.WorkItemCraftRewards)
                .HasForeignKey(d => d.CraftId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.WorkItemCraftRewards)
                .HasForeignKey(d => d.WorkItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WorkItemOccurrence>(entity =>
        {
            entity.HasIndex(e => e.PublicId, "IXU_WorkItemOccurrences_PublicId").IsUnique();

            entity.HasIndex(e => new { e.ScheduleId, e.ScheduledStartAt }, "IXU_WorkItemOccurrences_ScheduleId_ScheduledStartAt")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.HasIndex(e => new { e.WorkItemId, e.ScheduledStartAt }, "IX_WorkItemOccurrences_WorkItemId_ScheduledStartAt").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.PublicId).HasDefaultValueSql("NEWID()");

            entity.HasOne(d => d.Schedule).WithMany(p => p.WorkItemOccurrences)
                .HasForeignKey(d => d.ScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Status).WithMany(p => p.WorkItemOccurrences)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.WorkItemOccurrences)
                .HasForeignKey(d => d.WorkItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WorkItemSchedule>(entity =>
        {
            entity.HasIndex(e => e.WorkItemId, "IX_WorkItemSchedules_WorkItemId").HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.DaysOfWeek).HasMaxLength(50);
            entity.Property(e => e.Interval).HasDefaultValue(1);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.TimeZone)
                .HasMaxLength(100)
                .HasDefaultValue("UTC");

            entity.HasOne(d => d.RecurrenceType).WithMany(p => p.WorkItemSchedules).HasForeignKey(d => d.RecurrenceTypeId);

            entity.HasOne(d => d.ScheduleType).WithMany(p => p.WorkItemSchedules)
                .HasForeignKey(d => d.ScheduleTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.WorkItemSchedules)
                .HasForeignKey(d => d.WorkItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WorkItemSkillReward>(entity =>
        {
            entity.HasIndex(e => new { e.WorkItemId, e.SkillId }, "IXU_WorkItemSkillRewards_WorkItemId_SkillId")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");

            entity.HasOne(d => d.Skill).WithMany(p => p.WorkItemSkillRewards)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.WorkItemSkillRewards)
                .HasForeignKey(d => d.WorkItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WorkItemStatus>(entity =>
        {
            entity.HasIndex(e => e.Code, "IXU_WorkItemStatuses_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<WorkItemTag>(entity =>
        {
            entity.HasIndex(e => new { e.WorkItemId, e.TagId }, "IXU_WorkItemTags_WorkItemId_TagId")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");

            entity.HasOne(d => d.Tag).WithMany(p => p.WorkItemTags)
                .HasForeignKey(d => d.TagId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.WorkItem).WithMany(p => p.WorkItemTags)
                .HasForeignKey(d => d.WorkItemId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<WorkItemType>(entity =>
        {
            entity.HasIndex(e => e.Code, "IXU_WorkItemTypes_Code")
                .IsUnique()
                .HasFilter("[DeletedAt] IS NULL");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}